dataset:
  data_path: /mnt/07765B7E452A5B73/Machine Learning/Dogs/
  prepared_data_path: /mnt/07765B7E452A5B73/Machine Learning/Dogs/processing
  prepared_data: False
  prepared_data_size: 1024
output:
  output_path: ./output
  output_images_path: ./output/images

model:
  #  TODO: zastanowić się, czy to jest potrzebne
  file: .model/dcgan2.py
  discriminator:
    activation: leakRelu(0.2)
    dropout: 0.2
    auto_add_layers: conv
    kernel_size: 4
    depth: 128
    strides: 2
    input_shape: (64,64,3)
    layers: >
      conv(1);
      conv(2);
      conv(4);
      conv(8);

  generator:
    activation: relu
    dropout: -1
    auto_add_layers: conv
    kernel_size: 4
    depth: 128
    input_shape: 100
    layers: >
      dense(128);
      reshape(4, 4, 8);
      upscaling();
      conv(8);
      upscaling();
      conv(4);
      upscaling();
      conv(2);
      upscaling();
      conv(1);

train:
  loader: generator
  epochs: 1000
  batch_size: 16
  save_result_interval: 10
  discriminator_iterations: 2
  discriminator_labels_weight: 0.9
  discriminator:
    labels_weight: 0.9
    optimizer: adam
    learning_rate: 0.0001
    beta: 0.5
    loss: binary_crossentropy
  generator:
    optimizer: adam
    learning_rate: 0.0001
    beta: 0.5
    loss: binary_crossentropy
  gan:
    optimizer: adam
    learning_rate: 0.0001
    beta: 0.5
    loss: binary_crossentropy



